controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    wheel_controller:
      type: forward_command_controller/ForwardCommandController

wheel_controller:
  ros__parameters:
    joints:
      - front_left_wheel_joint
      - front_right_wheel_joint
      - rear_left_wheel_joint
      - rear_right_wheel_joint
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - velocity
      - position

gazebo_ros2_control:
  ros__parameters:
    use_sim_time: true
    robot_sim_type: "gazebo_ros2_control/DefaultRobotHWSim"